/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.figuras;

import java.io.*;

/**
 *
 * @author USUARIO
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBase = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        txtRadio = new javax.swing.JTextField();
        btnCuadrado = new javax.swing.JButton();
        btnRectangulo = new javax.swing.JButton();
        btnCirculo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtLado = new javax.swing.JTextField();
        btnTriangulo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMayor = new javax.swing.JTextField();
        txtMenor = new javax.swing.JTextField();
        btnRombo = new javax.swing.JButton();
        btnAcerca = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtGrado = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtNG = new javax.swing.JTextField();
        txtEG = new javax.swing.JTextField();
        txtGG = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Areas de figuras geometricas");
        setBackground(new java.awt.Color(51, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingrese base");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jLabel2.setText("Ingrese altura");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        jLabel3.setText("Ingrese radio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txtBase.setBackground(new java.awt.Color(255, 255, 204));
        txtBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBaseActionPerformed(evt);
            }
        });
        getContentPane().add(txtBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 80, -1));

        txtAltura.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(txtAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 80, -1));

        txtRadio.setBackground(new java.awt.Color(255, 255, 204));
        txtRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRadioActionPerformed(evt);
            }
        });
        getContentPane().add(txtRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 80, -1));

        btnCuadrado.setBackground(new java.awt.Color(102, 255, 255));
        btnCuadrado.setText("Cuadrado");
        btnCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuadradoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 90, -1));

        btnRectangulo.setBackground(new java.awt.Color(51, 255, 255));
        btnRectangulo.setText("Rectangulo");
        btnRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectanguloActionPerformed(evt);
            }
        });
        getContentPane().add(btnRectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 109, -1));

        btnCirculo.setBackground(new java.awt.Color(51, 255, 255));
        btnCirculo.setText("Circulo");
        btnCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCirculoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCirculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel4.setText("Resultado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        txtResultado.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 161, -1));

        btnLimpiar.setBackground(new java.awt.Color(51, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        btnSalir.setBackground(new java.awt.Color(51, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));

        jLabel5.setText("Ingrese lado");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtLado.setBackground(new java.awt.Color(255, 255, 204));
        txtLado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLadoActionPerformed(evt);
            }
        });
        getContentPane().add(txtLado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 60, -1));

        btnTriangulo.setBackground(new java.awt.Color(51, 255, 255));
        btnTriangulo.setText("Triangulo");
        btnTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrianguloActionPerformed(evt);
            }
        });
        getContentPane().add(btnTriangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 80, -1));

        jLabel6.setText("G");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 11, -1));

        jLabel7.setText("M");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        jLabel8.setText("U");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        jLabel9.setText("Diagonal mayor");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        jLabel10.setText("Diagonal menor");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        txtMayor.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(txtMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 70, -1));

        txtMenor.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(txtMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 70, -1));

        btnRombo.setBackground(new java.awt.Color(51, 255, 255));
        btnRombo.setText("Rombo");
        btnRombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRomboActionPerformed(evt);
            }
        });
        getContentPane().add(btnRombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        btnAcerca.setBackground(new java.awt.Color(51, 255, 255));
        btnAcerca.setText("Mis datos");
        btnAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        jLabel11.setText("Nombre");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel12.setText("Edad");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jLabel13.setText("Grado");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        txtNombre.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 120, -1));

        txtGrado.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(txtGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 110, -1));

        txtEdad.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 40, -1));

        txtNG.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(txtNG, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 130, -1));

        txtEG.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(txtEG, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 80, -1));

        txtGG.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(txtGG, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 130, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 450, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 460, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuadradoActionPerformed
        // TODO add your handling code here:
       double lado = Double.parseDouble(txtLado.getText());
       txtResultado.setText(String.valueOf(lado * lado));
    }//GEN-LAST:event_btnCuadradoActionPerformed

    private void btnRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectanguloActionPerformed
        // TODO add your handling code here:
         double base = Double.parseDouble(txtAltura.getText());
        double altura = Double.parseDouble(txtBase.getText());
        txtResultado.setText(String.valueOf(base * altura));
    }//GEN-LAST:event_btnRectanguloActionPerformed

    private void btnCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCirculoActionPerformed
        // TODO add your handling code here:
        double radio = Double.parseDouble(txtRadio.getText());
        txtResultado.setText(String.valueOf(3.1416 * (radio*radio)));
    }//GEN-LAST:event_btnCirculoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtBase.setText("");
        txtAltura.setText("");
        txtRadio.setText("");
        txtLado.setText("");
         txtMayor.setText("");
        txtMenor.setText("");
        txtResultado.setText("");
         txtNombre.setText("");
        txtEdad.setText("");
        txtGrado.setText("");
         txtNG.setText("");
        txtEG.setText("");
        txtGG.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRadioActionPerformed

    }//GEN-LAST:event_txtRadioActionPerformed

    private void btnTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrianguloActionPerformed
        // TODO add your handling code here:
         double base = Double.parseDouble(txtAltura.getText());
        double altura = Double.parseDouble(txtBase.getText());
        txtResultado.setText(String.valueOf((base * altura)/2));
    }//GEN-LAST:event_btnTrianguloActionPerformed

    private void txtLadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLadoActionPerformed
   
    }//GEN-LAST:event_txtLadoActionPerformed

    private void txtBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBaseActionPerformed

    private void btnRomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRomboActionPerformed
        // TODO add your handling code here:
        double mayor = Double.parseDouble(txtMayor.getText());
        double menor = Double.parseDouble(txtMenor.getText());
        txtResultado.setText(String.valueOf((mayor * menor)/2));
    }//GEN-LAST:event_btnRomboActionPerformed

    private void btnAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaActionPerformed
        // TODO add your handling code here:
        
        String nombre = txtNombre.getText();
        String edad = txtEdad.getText();
        String grado = txtGrado.getText();
        
        alumno a = new alumno(nombre,edad,grado);
        System.out.println(a.mostrar());
        txtNG.setText(nombre);
        txtEG.setText(edad);
        txtGG.setText(grado);
        
        txtNombre.setText("");
        txtEdad.setText("");
        txtGrado.setText("");
        
        
        BufferedWriter bw = null;
    FileWriter fw = null;

    try {
        String data = a.mostrar();
        File file = new File("archivo.txt");
        // Si el archivo no existe, se crea!
        if (!file.exists()) {
            file.createNewFile();
        }
        // flag true, indica adjuntar información al archivo.
        fw = new FileWriter(file.getAbsoluteFile(), true);
        bw = new BufferedWriter(fw);
        bw.write(data);
        System.out.println("información agregada!");
    } catch (IOException e) {
        e.printStackTrace();
    } finally {
        try {
                        //Cierra instancias de FileWriter y BufferedWriter
            if (bw != null)
                bw.close();
            if (fw != null)
                fw.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
        
       
        
    }//GEN-LAST:event_btnAcercaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>
        
alumno a = new alumno("","","");

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
        
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcerca;
    private javax.swing.JButton btnCirculo;
    private javax.swing.JButton btnCuadrado;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRectangulo;
    private javax.swing.JButton btnRombo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTriangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtBase;
    private javax.swing.JTextField txtEG;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtGG;
    private javax.swing.JTextField txtGrado;
    private javax.swing.JTextField txtLado;
    private javax.swing.JTextField txtMayor;
    private javax.swing.JTextField txtMenor;
    private javax.swing.JTextField txtNG;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRadio;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
